### ISSUE TITLE
Store wind data in a database

### ISSUE THREAD

**Issue by NickRoach** [NickRoach/blackheath-wind-meter#67]
Depends on #66 

The json file is not good because the frontend has to retrieve all of the file before it can display the current 10-minute period of readings.
Also, historical data is discarded. It seems wrong to discard such hard-won data.
Instead we should use a database to store the data and allow the retrieval of one time segment at a time.
Let's use Dynamo DB for that. Let's continue to use the lambda rather than having a more-complex backend service. This is a good opportunity to convert the lambda to Typescript.

We need to do a few separate things to make that happen:

- [ ] Deploy a Dynamo DB to run on AWS using code that is contained in the repo. Do with pulumi
- [ ] #99 Convert the lambda function to typescript and modify the deployment action to transpile it and deploy the result
- [ ] Change the lambda function to put things into the database when it receives a post from the wind gauge
- [ ] Change the lambda function to respond to requests that specify a time stamp
- [ ] Change the frontend to make requests for a specific time stamp
- [ ] Deal with the case where the wind gauge misses a post. "No data received" message
- [ ] Have the frontend store the data that it has already retrieved so that it doesn't re-request it. A simple POJO will do
- [ ] #101 

Next steps: Instead of retrieving data one timestamp at a time, instead retrieve, say, 6 timestamps prior to the timestamp the user is currently looking at

**Comment by burtscriptor** [comment]
I'd like to have a go at two and three. I don't know what a lambda function is but ill be finding out. It sounds like roughly speaking the lambda is the middle man between the windstation and frontend.

I'd also like to have a go at six when it comes time.
